FROM microsoft/dotnet:1.1.0-sdk-projectjson

RUN apt-get update && apt-get install -y --no-install-recommends xsltproc

# inject hostnames needed within job test container
ENV JobEndPoint http://jobhost:5000
ENV APIEndPoint http://apihost:5000

COPY . /app

WORKDIR /app

RUN mkdir output

RUN ["dotnet", "restore"]

WORKDIR /app/OnDemandTools.Jobs.Tests

RUN ["dotnet", "build"]

CMD dotnet test -xml /app/output/jobrun.xml && \
    xsltproc --output /app/output/jobresults.xml --stringparam use.extensions 0 /app/xunit-to-junit.xslt /app/output/jobrun.xml