FROM microsoft/dotnet:1.1.0-sdk-projectjson

RUN apt-get update && apt-get install -y --no-install-recommends xsltproc

# inject hostnames needed within job test container
ENV JobEndPoint http://jobhost:5000
ENV APIEndPoint http://apihost:5000

COPY . /app

WORKDIR /app

RUN mkdir output

WORKDIR /app/OnDemandTools.Jobs.Tests

RUN ["dotnet", "build"]

CMD ["/bin/bash", "./tests.sh"]