FROM josephbulger/dotnetnode:1.1.0-sdk-projectjson-6.5.0-node

RUN apt-get update && apt-get install -y --no-install-recommends xsltproc

COPY . /app

WORKDIR /app

RUN mkdir output

RUN ["dotnet", "restore"]