FROM microsoft/dotnet:1.1.0-sdk-projectjson

RUN apt-get update && apt-get install -y --no-install-recommends xsltproc

# inject hostname needed within api test container
ENV APIEndPoint http://apihost:5000

COPY . /app

WORKDIR /app

RUN mkdir output

RUN ["dotnet", "restore"]

WORKDIR /app/OnDemandTools.API.Tests

RUN ["dotnet", "build"]

CMD dotnet test -xml /app/output/apirun.xml && \
    xsltproc --output /app/output/apiresults.xml --stringparam use.extensions 0 /app/xunit-to-junit.xslt /app/output/apirun.xml