FROM josephbulger/odtbase

RUN apt-get update && apt-get install -y --no-install-recommends xsltproc

COPY . /app

WORKDIR /app

RUN mkdir output

RUN dotnet restore

WORKDIR /app/OnDemandTools.API

RUN dotnet publish -c Release

WORKDIR /app/OnDemandTools.API.Tests

RUN dotnet build

WORKDIR /app/OnDemandTools.Jobs

RUN dotnet publish -c Release

WORKDIR /app/OnDemandTools.Jobs.Tests

RUN dotnet build

WORKDIR /app/OnDemandTools.Web

RUN npm run portal

RUN dotnet publish -c Release
