FROM microsoft/dotnet:1.1.0-sdk-projectjson

COPY . /app

WORKDIR /app

RUN ls | xargs echo

RUN ["dotnet", "restore"]

WORKDIR /app/OnDemandTools.Business.Tests

RUN ["dotnet", "build"]

RUN ["dotnet", "test"]


WORKDIR /app/OnDemandTools.API

RUN ["dotnet", "build"]

CMD ["dotnet", "run", "--server.urls", "http://*:5000"]