FROM microsoft/dotnet:1.1.0-sdk-projectjson

RUN apt-get update && apt-get install -y --no-install-recommends \
		xsltproc

# inject hostname needed within api test container
ENV APIEndPoint http://apihost:5000

COPY . /app

WORKDIR /app

RUN mkdir testrun
RUN mkdir output
RUN mkdir output/xunit

RUN ["dotnet", "restore"]

WORKDIR /app/OnDemandTools.API.Tests

RUN ["dotnet", "build"]

CMD curl --retry 1 --retry-delay 2 -v http://apihost:5000/healthcheck && \
    dotnet test -xml /app/testrun/apirun.xml && \
    xsltproc --output /app/output/xunit/apiresults.xml --stringparam use.extensions 0 /app/xunit-to-junit.xslt /app/testrun/apirun.xml