//placeholder to provider all the Action Reducer Name
export const FETCH_USERDETAILS_SUCCESS = 'FETCH_USERDETAILS_SUCCESS';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_QUEUES_SUCCESS = 'FETCH_QUEUES_SUCCESS';
export const SAVE_QUEUE_SUCCESS = 'SAVE_QUEUE_SUCCESS';
export const FETCH_SIGNALRQUEUES_SUCCESS = 'FETCH_SIGNALRQUEUES_SUCCESS';
export const FETCH_NOTIFICATIONHISTORY_SUCCESS = 'FETCH_NOTIFICATIONHISTORY_SUCCESS';
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FILTER_QUEUES_SUCCESS = 'FILTER_QUEUES_SUCCESS';
export const DELETE_QUEUE_SUCCESS = 'DELETE_QUEUE_SUCCESS';


//destination Action Reducer Name
export const FETCH_DESTINATIONS_SUCCESS = 'FETCH_DESTINATIONS_SUCCESS';
export const FILTER_DESTINATION_SUCCESS = 'FILTER_DESTINATION_SUCCESS';
export const SAVE_DESTINATION_SUCCESS = 'SAVE_DESTINATION_SUCCESS';
export const DELETE_DESTINATION_SUCCESS = 'DELETE_DESTINATION_SUCCESS';

//product Action Reducer Name
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

//Title Search Action Reducer Name
export const TITLE_SEARCH_SUCCESS = 'TITLE_SEARCH_SUCCESS';
export const CLEAR_TITLE_SUCCESS = 'CLEAR_TITLE_SUCCESS';
