//placeholder to provider all the Action Reducer Name
export const FETCH_USERDETAILS_SUCCESS = 'FETCH_USERDETAILS_SUCCESS';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_QUEUES_SUCCESS = 'FETCH_QUEUES_SUCCESS';
export const SAVE_QUEUE_SUCCESS = 'SAVE_QUEUE_SUCCESS';
export const FETCH_SIGNALRQUEUES_SUCCESS = 'FETCH_SIGNALRQUEUES_SUCCESS';
export const FETCH_NOTIFICATIONHISTORY_SUCCESS = 'FETCH_NOTIFICATIONHISTORY_SUCCESS';