//placeholder to provider all the Action Reducer Name
export const FETCH_USERDETAILS_SUCCESS = 'FETCH_USERDETAILS_SUCCESS';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_QUEUES_SUCCESS = 'FETCH_QUEUES_SUCCESS';
export const SAVE_QUEUE_SUCCESS = 'SAVE_QUEUE_SUCCESS';
export const FETCH_SIGNALRQUEUES_SUCCESS = 'FETCH_SIGNALRQUEUES_SUCCESS';
export const FETCH_NOTIFICATIONHISTORY_SUCCESS = 'FETCH_NOTIFICATIONHISTORY_SUCCESS';
export const DELETE_QUEUE_SUCCESS = 'DELETE_QUEUE_SUCCESS';


//destination Action Reducer Name
export const FETCH_DESTINATIONS_SUCCESS = 'FETCH_DESTINATIONS_SUCCESS';
export const SAVE_DESTINATION_SUCCESS = 'SAVE_DESTINATION_SUCCESS';
export const DELETE_DESTINATION_SUCCESS = 'DELETE_DESTINATION_SUCCESS';

//category Action Reducer Name
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const SAVE_CATEGORIES_SUCCESS = 'SAVE_CATEGORIES_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const CATEGORY_EXPAND_ROW_CLICK_SUCCESS = 'CATEGORY_EXPAND_ROW_CLICK_SUCCESS';

//product Action Reducer Name
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';

//Title Search Action Reducer Name
export const TITLE_SEARCH_SUCCESS = 'TITLE_SEARCH_SUCCESS';
export const FILTER_TITLE_SUCCESS = 'FILTER_TITLE_SUCCESS';
export const CLEAR_TITLE_SUCCESS = 'CLEAR_TITLE_SUCCESS';


//status Action Reducer Name
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';
export const SAVE_STATUS_SUCCESS = 'SAVE_STATUS_SUCCESS';


//content tier Action Reducer Name
export const FETCH_CONTENT_TIER_SUCCESS = 'FETCH_CONTENT_TIER_SUCCESS';
export const SAVE_CONTENT_TIER_SUCCESS = 'SAVE_CONTENT_TIER_SUCCESS';
export const DELETE_CONTENT_TIER_SUCCESS = 'DELETE_CONTENT_TIER_SUCCESS';
export const CONTENT_TIER_CLICK_SUCCESS = 'CONTENT_TIER_CLICK_SUCCESS';


//airing Id distribution Action Reducer Name
export const FETCH_AIRINGID_SUCCESS = 'FETCH_AIRINGID_SUCCESS';
export const DELETE_AIRINGID_SUCCESS = 'DELETE_AIRINGID_SUCCESS';
export const SAVE_AIRINGID_SUCCESS = 'SAVE_AIRINGID_SUCCESS';


/// Action types specifically for Path translations
export const FETCH_PATHTRANSLATION_SUCCESS = 'FETCH_PATHTRANSLATION_SUCCESS';
export const SAVE_PATHTRANSLATION_SUCCESS = 'SAVE_PATHTRANSLATION_SUCCESS';
export const DELETE_PATHTRANSLATION_SUCCESS = 'DELETE_PATHTRANSLATION_SUCCESS';

/// Action types specifically for Path translations
export const FETCH_PERMISSION_SUCCESS = 'FETCH_PERMISSION_SUCCESS';
export const SAVE_PERMISSION_SUCCESS = 'SAVE_PERMISSION_SUCCESS';

/// Action types specifically used for Application errors/handling
export const APPLICATION_API_ERROR = 'APPLICATION_API_ERROR';

/// Action types specifically used for session handling
export const TIMER_SUCCESS = 'TIMER_SUCCESS';
