version: 2
jobs:
  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2

    branches:
      only:
        - dev
        - rc
        - sandbox
        - newbuild
        
    working_directory: ~/app

    steps:
      - checkout

      - setup_remote_docker

      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Building App
          working_directory: ~/app/Deployment
          command: |
            docker-compose build

      - run:
          name: Make Testbed
          working_directory: ~/app
          command: |
            mkdir output
            mkdir output/xunit
            
      - run:
          name: Testing API
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose run --name apitest odt-api-tests
            docker cp apitest:/app/output/xunit ~/app/output/xunit
            docker-compose down

      - run:
          name: Testing Jobs
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose run --name jobtest odt-jobs-tests
            docker cp jobtest:/app/output/xunit ~/app/output/xunit
            docker-compose down
      
      - store_artifacts:
          path: ~/app/output
        
      - store_test_results:
          path: ~/app/output
           