version: 2
jobs:
  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2

    working_directory: /Deployment

    steps:
      - checkout

      - setup_remote_docker

      - run: 
        name: Docker Compose Building
        command: docker-compose build