version: 2
jobs:
  build:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    branches:
      only:
        - dev
        - rc
        - sandbox
        - newbuild
        
    working_directory: ~/app

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Building App
          working_directory: ~/app/Deployment
          command: |
            docker-compose build odt-build
            docker-compose run -d --name built odt-build
            mkdir ~/app/output
            mkdir ~/app/output/API
            mkdir ~/app/output/JOBS
            mkdir ~/app/output/WEB            
            docker cp built:/app/OnDemandTools.API/bin/Release/netcoreapp1.1/publish ~/app/output/API
            docker cp built:/app/OnDemandTools.Jobs/bin/Release/netcoreapp1.1/publish ~/app/output/JOBS
            docker cp built:/app/OnDemandTools.Web/bin/Release/netcoreapp1.1/publish ~/app/output/WEB
            docker-compose down
            docker-compose build odtapi odtwebapp odtjobs odt-api-tests odt-jobs-tests

      - run:
          name: Make Test Harness
          working_directory: ~/app
          command: |
            mkdir ~/app/tests
            mkdir ~/app/tests/xunit

      - run:
          name: Testing API
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose run --name apitest odt-api-tests
            BOMBED=$?
            docker cp apitest:/app/output/apiresults.xml ~/app/tests/xunit
            exit $BOMBED

      - run:
          name: Testing Jobs
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose run --name jobtest odt-jobs-tests
            BOMBED=$?
            docker cp jobtest:/app/output/jobresults.xml ~/app/tests/xunit
            exit $BOMBED

      - run:
          name: Spin down Test Harness
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose down            
      
      - store_artifacts:
          path: ~/app/tests
        
      - store_test_results:
          path: ~/app/tests

      - run:
          name: Log into Quay          
          command: |
            docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" -e="." quay.io  

      - run:
          name: Push Image into Quay
          working_directory: ~/app/Deployment
          command: |
            export COMPOSE_HTTP_TIMEOUT=600
            docker-compose push odt-api odt-webapp odt-jobs          

      - run:
          name: Continious Integration
          working_directory: ~/app/Deployment
          command: |
              if [ "${CIRCLE_BRANCH}" == "rc" ] || [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "newbuild" ]; then
                harbor-compose catalog;
              fi

      - run:
          name: Continious Deployment to Dev
          working_directory: ~/app/Deployment
          command: |
              if [ "${CIRCLE_BRANCH}" == "dev" ]; then
                harbor-compose deploy -e dev;
              fi

      - run:
          name: Continious Deployment to Sandbox
          working_directory: ~/app/Deployment
          command: |
              if [ "${CIRCLE_BRANCH}" == "sandbox" ]; then
                harbor-compose deploy -e sandbox;
              fi
           
           