version: 2
jobs:
  build:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    branches:
      only:
        - dev
        - rc
        - sandbox
        - newbuild
        
    working_directory: ~/app

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Building App
          working_directory: ~/app/Deployment
          command: |
            docker-compose build odt-build
            docker-compose run -d --name built odt-build
            mkdir ~/app/output
            mkdir ~/app/output/API
            mkdir ~/app/output/JOBS
            mkdir ~/app/output/WEB            
            docker cp built:/app/OnDemandTools.API/bin/Release/netcoreapp1.1/publish ~/app/output/API
            docker cp built:/app/OnDemandTools.Jobs/bin/Release/netcoreapp1.1/publish ~/app/output/JOBS
            docker cp built:/app/OnDemandTools.Web/bin/Release/netcoreapp1.1/publish ~/app/output/WEB
            docker-compose down
            docker-compose build odtapi odtwebapp odtjobs odt-api-tests odt-jobs-tests

  test-harness:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app

    steps:
      - run:
          name: Make Test Harness
          working_directory: ~/app
          command: |
            mkdir ~/app/tests
            mkdir ~/app/tests/xunit

  test-api:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app
    steps:
      - run:
          name: Testing API
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose run --name apitest odt-api-tests
            BOMBED=$?
            docker cp apitest:/app/output/apiresults.xml ~/app/tests/xunit
            exit $BOMBED

  test-jobs:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app

    steps:
      - run:
          name: Testing Jobs
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose run --name jobtest odt-jobs-tests
            BOMBED=$?
            docker cp jobtest:/app/output/jobresults.xml ~/app/tests/xunit
            exit $BOMBED

  test-spin-down:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app

    steps:
      - run:
          name: Spin down Test Harness
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose down   

  test-store:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app

    steps:
      - store_artifacts:
          path: ~/app/tests
        
      - store_test_results:
          path: ~/app/tests

  deploy-image:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app

    steps:
      - run:
          name: Log into Quay          
          command: |
            docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" -e="." quay.io  

      - run:
          name: Push Image into Quay
          working_directory: ~/app/Deployment
          command: |
            export COMPOSE_HTTP_TIMEOUT=600
            docker-compose push odtapi odtwebapp odtjobs  

  deploy-catalog:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app

    steps:
      - run:
            name: Continious Integration
            working_directory: ~/app/Deployment
            command: harbor-compose catalog;

  deploy-dev:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app

    steps:
      - run:
            name: Continious Deployment to Dev
            working_directory: ~/app/Deployment
            command: harbor-compose deploy -e dev;                    

  deploy-sandbox:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    working_directory: ~/app
    
    steps:
      - run:
            name: Continious Deployment to Sandbox
            working_directory: ~/app/Deployment
            command: harbor-compose deploy -e sandbox;                
           
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test-harness:
          requires:
            - build
      - test-api:
          requires:
            - test-harness
      - test-jobs:
          requires:
            - test-harness
      - test-spin-down:
          requires:
            - test-api
            - test-jobs
      - test-store:
          requires:
            - test-api
            - test-jobs
      - deploy-image:
          requires:
            - test-api
            - test-jobs
      - deploy-catalog:
          filters:
            branches:
              only:
                - rc
                - master
                - newbuild
          requires:
            - deploy-image
      - deploy-dev:
          filters:
            branches:
              only:
                - dev
          requires:
            - deploy-image
      - deploy-sandbox:
          filters:
            branches:
              only:
                - sandbox
          requires:
            - deploy-image
          
  