version: 2
jobs:
  build:
    docker:
      - image: quay.io/turner/harbor-cicd:0.0.1

    branches:
      only:
        - dev
        - rc
        - sandbox
        - newbuild
        
    working_directory: ~/app

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Building App
          working_directory: ~/app/Deployment
          command: |
            docker-compose build

      - run:
          name: Make Testbed
          working_directory: ~/app
          command: |
            mkdir output
            mkdir output/xunit

      - run:
          name: Testing API
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose run --name apitest odt-api-tests
            BOMBED=$?
            docker cp apitest:/app/output/apiresults.xml ~/app/output/xunit
            docker-compose down
            exit $BOMBED

      - run:
          name: Testing Jobs
          working_directory: ~/app/Deployment
          command: |
            set +e
            docker-compose run --name jobtest odt-jobs-tests
            BOMBED=$?
            docker cp jobtest:/app/output/jobresults.xml ~/app/output/xunit
            docker-compose down
            exit $BOMBED
      
      - store_artifacts:
          path: ~/app/output
        
      - store_test_results:
          path: ~/app/output

      - run:
          name: Log into Quay          
          command: |
            docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" -e="." quay.io  

      - run:
          name: Push Image into Quay
          working_directory: ~/app/Deployment
          command: docker-compose push            

      - run:
          name: Continious Integration
          working_directory: ~/app/Deployment
          command: |
              if [ "${CIRCLE_BRANCH}" == "rc" ] || [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "newbuild" ]; then
                cat harbor-compose.yml;
                harbor-compose catalog;
              fi

      - run:
          name: Continious Deployment to Dev
          working_directory: ~/app/Deployment
          command: |
              if [ "${CIRCLE_BRANCH}" == "dev" ];
                then harbor-compose deploy -e dev;
              fi

      - run:
          name: Continious Deployment to Sandbox
          working_directory: ~/app/Deployment
          command: |
              if [ "${CIRCLE_BRANCH}" == "sandbox" ];
                then harbor-compose deploy -e sandbox;
              fi
           