//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandTools.Jobs.Tests.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnDemandTools.Jobs.Tests.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;assetId&quot;: &quot;TBSE1001241700000243&quot;,&quot;Name&quot;:&quot;Our Other Cops Is On !, Part 2&quot;,&quot;Type&quot;:&quot;Episode (Non-Animated)&quot;,&quot;Brand&quot;:&quot;TBS&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2013-09-11T11:30:00Z&quot;,&quot;AiringId&quot;:7108144,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1223,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-14&quot;,&quot;Description&quot;:&quot;D,L,S,V&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;When Randy is about to turn off the prison TV, another Camden episode of \&quot;COPS\&quot; is shown, this time it evolves around the events on Independence Day.&quot;,&quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AiringWithSingleFlight {
            get {
                return ResourceManager.GetString("AiringWithSingleFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;AiringId&quot;:&quot;&quot;,&quot;Name&quot;:&quot;ProhibitResendMediaId&quot;,&quot;Type&quot;:&quot;Episode (Animated)&quot;,&quot;Brand&quot;:&quot;Cartoon&quot;,
        ///    &quot;Platform&quot;:&quot;Broadband&quot;,
        ///    &quot;Airings&quot;:[{&quot;Date&quot;:&quot;2016-11-02T23:00:00Z&quot;,&quot;AiringId&quot;:7906010,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1390,&quot;DisplayMinutes&quot;:30}
        ///    ,&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-PG&quot;,&quot;Description&quot;:&quot;&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;At the top of Dead Mountain, Finn discovers a treasure that comes with a terrible price.&quot;,&quot;Short&quot;:&quot;&quot;},
        ///    &quot;ReleaseYear&quot;:2016,&quot;Keywords&quot;:&quot;Eyes, Magic, Metamorphosis, Self-e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CartoonProhibitResendMediaId {
            get {
                return ResourceManager.GetString("CartoonProhibitResendMediaId", resourceCulture);
            }
        }
    }
}
