version: '2'

services:
  odtapi:
    env_file:
      - ./env/shared.env
      - ./env/api.env
    build: 
      context: ../
      dockerfile: Dockerfile.api
    image: quay.io/turner/odt-api:${VERSION}.${CIRCLE_BUILD_NUM}
    ports:
      - "5000:5000"
    environment:
        HEALTHCHECK: /v1/healthcheck
        PORT: "5000"
    
  