//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandTools.Business.Tests.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AiringBusinessResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal AiringBusinessResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnDemandTools.Business.Tests.Resources.AiringBusinessResource", typeof(AiringBusinessResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;airingId&quot;: &quot;TBSE1001241700000243&quot;,&quot;mediaId&quot;: &quot;eb1b27b9778ed037b564a68b72ec1da9a03a41ef&quot;,&quot;name&quot;: &quot;Parkie Awards, The&quot;,
        ///  &quot;type&quot;: &quot;Episode (Animated)&quot;,
        ///  &quot;brand&quot;: &quot;TBS&quot;,
        ///  &quot;platform&quot;: &quot;Cable&quot;,
        ///  &quot;airings&quot;: [
        ///    {
        ///      &quot;date&quot;: &quot;2016-12-07T11:00:00Z&quot;,
        ///      &quot;airingId&quot;: 8152316,
        ///      &quot;linked&quot;: true
        ///    }
        ///  ],
        ///  &quot;duration&quot;: {
        ///    &quot;lengthInSeconds&quot;: 1354,
        ///    &quot;displayMinutes&quot;: 30
        ///  },
        ///  &quot;title&quot;: {
        ///    &quot;rating&quot;: {},
        ///    &quot;storyLine&quot;: {
        ///      &quot;long&quot;: &quot;After Benson doesn&apos;t take home the award for Park Manager of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSEAiring {
            get {
                return ResourceManager.GetString("TBSEAiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  { &quot;AssetId&quot; : &quot;TBSE1001241700000243&quot;, &quot;MediaId&quot; : &quot;eb1b27b9778ed037b564a68b72ec1da9a03a41ef&quot;, &quot;Name&quot; : &quot;Parkie Awards, The&quot;, &quot;Type&quot; : &quot;Episode (Animated)&quot;, &quot;Network&quot; : &quot;TBS&quot;, &quot;Platform&quot; : &quot;Cable&quot;, &quot;Airings&quot; : [ { &quot;Date&quot; : &quot;2016-12-07T11:00:00.00Z&quot; , &quot;AiringId&quot; : 8152316, &quot;Linked&quot; : true } ], &quot;Duration&quot; : { &quot;LengthInSeconds&quot; : 1354, &quot;DisplayMinutes&quot; : 30 }, &quot;Title&quot; : { &quot;TVRating&quot; : {  }, &quot;StoryLine&quot; : { &quot;Long&quot; : &quot;want to make him feel like a winner.&quot;, &quot;Short&quot; : &quot; the guys want to make him feel like a winner. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSEHistoryflightEnddateModified {
            get {
                return ResourceManager.GetString("TBSEHistoryflightEnddateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  { &quot;AssetId&quot; : &quot;TBSE1001241700000243&quot;, &quot;MediaId&quot; : &quot;eb1b27b9778ed037b564a68b72ec1da9a03a41ef&quot;, &quot;Name&quot; : &quot;Parkie Awards, The&quot;, &quot;Type&quot; : &quot;Episode (Animated)&quot;, &quot;Network&quot; : &quot;TBS&quot;, &quot;Platform&quot; : &quot;Cable&quot;, &quot;Airings&quot; : [ { &quot;Date&quot; : &quot;2016-12-07T11:00:00.00Z&quot; , &quot;AiringId&quot; : 8152316, &quot;Linked&quot; : true } ], &quot;Duration&quot; : { &quot;LengthInSeconds&quot; : 1354, &quot;DisplayMinutes&quot; : 30 }, &quot;Title&quot; : { &quot;TVRating&quot; : {  }, &quot;StoryLine&quot; : { &quot;Long&quot; : &quot;want to make him feel like a winner.&quot;, &quot;Short&quot; : &quot; the guys want to make him feel like a winner. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSEHistoryInitial {
            get {
                return ResourceManager.GetString("TBSEHistoryInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  { &quot;AssetId&quot; : &quot;TBSE1001241700000243&quot;, &quot;MediaId&quot; : &quot;eb1b27b9778ed037b564a68b72ec1da9a03a41ef&quot;, &quot;Name&quot; : &quot;Parkie Awards, The&quot;, &quot;Type&quot; : &quot;Episode (Animated)&quot;, &quot;Network&quot; : &quot;TBS&quot;, &quot;Platform&quot; : &quot;Cable&quot;, &quot;Airings&quot; : [ { &quot;Date&quot; : &quot;2016-12-07T11:00:00.00Z&quot; , &quot;AiringId&quot; : 8152316, &quot;Linked&quot; : true } ], &quot;Duration&quot; : { &quot;LengthInSeconds&quot; : 1354, &quot;DisplayMinutes&quot; : 30 }, &quot;Title&quot; : { &quot;TVRating&quot; : {  }, &quot;StoryLine&quot; : { &quot;Long&quot; : &quot;want to make him feel like a winner.&quot;, &quot;Short&quot; : &quot; the guys want to make him feel like a winner. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSEHistoryWithFightDateModified {
            get {
                return ResourceManager.GetString("TBSEHistoryWithFightDateModified", resourceCulture);
            }
        }
    }
}
