//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDemandTools.API.Tests.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnDemandTools.API.Tests.Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;Name&quot;:&quot;Don&apos;t Look&quot;,&quot;Type&quot;:&quot;Episode (Animated)&quot;,&quot;Brand&quot;:&quot;Cartoon&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2016-04-02T23:00:00Z&quot;,&quot;AiringId&quot;:7906079,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1390,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-PG&quot;,&quot;Description&quot;:&quot;&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;At the top of Dead Mountain, Finn discovers a treasure that comes with a terrible price.&quot;,&quot;Short&quot;:&quot;&quot;},&quot;ReleaseYear&quot;:2016,&quot;Keywords&quot;:&quot;Eyes, Magic, Metamorphosis, Self-esteem, Self-loathing&quot;,&quot;OriginalPremiereDate&quot;:&quot;201 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CartoonAiringWith3Flights {
            get {
                return ResourceManager.GetString("CartoonAiringWith3Flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;Name&quot;:&quot;Don&apos;t Look&quot;,&quot;Type&quot;:&quot;Episode (Animated)&quot;,&quot;Brand&quot;:&quot;Cartoon&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2016-04-02T23:00:00Z&quot;,&quot;AiringId&quot;:7906079,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1390,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-PG&quot;,&quot;Description&quot;:&quot;&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;At the top of Dead Mountain, Finn discovers a treasure that comes with a terrible price.&quot;,&quot;Short&quot;:&quot;&quot;},&quot;ReleaseYear&quot;:2016,&quot;Keywords&quot;:&quot;Eyes, Magic, Metamorphosis, Self-esteem, Self-loathing&quot;,&quot;OriginalPremiereDate&quot;:&quot;201 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CartoonAiringWithNoVersion {
            get {
                return ResourceManager.GetString("CartoonAiringWithNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;Name&quot;:&quot;Don&apos;t Look&quot;,&quot;Type&quot;:&quot;Episode (Animated)&quot;,&quot;Brand&quot;:&quot;Cartoon&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2016-04-02T23:00:00Z&quot;,&quot;AiringId&quot;:7906079,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1390,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-PG&quot;,&quot;Description&quot;:&quot;&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;At the top of Dead Mountain, Finn discovers a treasure that comes with a terrible price.&quot;,&quot;Short&quot;:&quot;&quot;},&quot;ReleaseYear&quot;:2016,&quot;Keywords&quot;:&quot;Eyes, Magic, Metamorphosis, Self-esteem, Self-loathing&quot;,&quot;OriginalPremiereDate&quot;:&quot;201 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CartoonAiringWithVersionCIDOrderChanged {
            get {
                return ResourceManager.GetString("CartoonAiringWithVersionCIDOrderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;AiringId&quot;:&quot;&quot;,&quot;Name&quot;:&quot;ProhibitResendMediaId&quot;,&quot;Type&quot;:&quot;Episode (Animated)&quot;,&quot;Brand&quot;:&quot;Cartoon&quot;,
        ///    &quot;Platform&quot;:&quot;Broadband&quot;,
        ///    &quot;Airings&quot;:[{&quot;Date&quot;:&quot;2016-11-02T23:00:00Z&quot;,&quot;AiringId&quot;:7906010,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1390,&quot;DisplayMinutes&quot;:30}
        ///    ,&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-PG&quot;,&quot;Description&quot;:&quot;&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;At the top of Dead Mountain, Finn discovers a treasure that comes with a terrible price.&quot;,&quot;Short&quot;:&quot;&quot;},
        ///    &quot;ReleaseYear&quot;:2016,&quot;Keywords&quot;:&quot;Eyes, Magic, Metamorphosis, Self-e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CartoonProhibitResendMediaId {
            get {
                return ResourceManager.GetString("CartoonProhibitResendMediaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[&quot;1111A&quot;],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;}.
        /// </summary>
        public static string DeletePackage_InvalidTitle {
            get {
                return ResourceManager.GetString("DeletePackage_InvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[&quot;1234&quot;],&quot;DestinationCode&quot;:&quot;TNTW&quot;}.
        /// </summary>
        public static string DeletePackage_TypeNotPresent {
            get {
                return ResourceManager.GetString("DeletePackage_TypeNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;AiringId&quot;:&quot;CARE1005021600011137&quot;,&quot;TitleIds&quot;:[1234,&quot;3456&quot;],&quot;ContentIds&quot;:[&quot;1G9C0&quot;,&quot;2K439&quot;],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_AllIdsPresent {
            get {
                return ResourceManager.GetString("InvalidPackage_AllIdsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[],&quot;ContentIds&quot;:[],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_BothIdsEmpty {
            get {
                return ResourceManager.GetString("InvalidPackage_BothIdsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_BothIdsNotPresent {
            get {
                return ResourceManager.GetString("InvalidPackage_BothIdsNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[1234,&quot;3456&quot;],&quot;ContentIds&quot;:[&quot;1G9C0&quot;,&quot;2K439&quot;],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_BothIdsPresent {
            get {
                return ResourceManager.GetString("InvalidPackage_BothIdsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[],&quot;ContentIds&quot;:[],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_ContentIdsEmpty {
            get {
                return ResourceManager.GetString("InvalidPackage_ContentIdsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_ContentIdsNotPresent {
            get {
                return ResourceManager.GetString("InvalidPackage_ContentIdsNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;AiringId&quot;:&quot;XXX&quot;,&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_InvalidAiringId {
            get {
                return ResourceManager.GetString("InvalidPackage_InvalidAiringId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_NoIdsPresent {
            get {
                return ResourceManager.GetString("InvalidPackage_NoIdsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[1234,&quot;3456&quot;],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:&quot;&quot;}.
        /// </summary>
        public static string InvalidPackage_PackageEmpty {
            get {
                return ResourceManager.GetString("InvalidPackage_PackageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[1234,&quot;3456&quot;],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;}.
        /// </summary>
        public static string InvalidPackage_PackageNotPresent {
            get {
                return ResourceManager.GetString("InvalidPackage_PackageNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[],&quot;ContentIds&quot;:[],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_TitleIdsEmpty {
            get {
                return ResourceManager.GetString("InvalidPackage_TitleIdsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;ContentIds&quot;:[],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_TitleIdsNotPresent {
            get {
                return ResourceManager.GetString("InvalidPackage_TitleIdsNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[1234,&quot;3456&quot;],&quot;ContentIds&quot;:[],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string InvalidPackage_TypeNotPresent {
            get {
                return ResourceManager.GetString("InvalidPackage_TypeNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;Name&quot;:&quot;Our Other Cops Is On !, Part 2&quot;,&quot;Type&quot;:&quot;Episode (Non-Animated)&quot;,&quot;Brand&quot;:&quot;TBS&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2013-09-11T11:30:00Z&quot;,&quot;AiringId&quot;:7108144,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1223,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-14&quot;,&quot;Description&quot;:&quot;D,L,S,V&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;When Randy is about to turn off the prison TV, another Camden episode of \&quot;COPS\&quot; is shown, this time it evolves around the events on Independence Day.&quot;,&quot;Short&quot;:&quot;When Randy is about to turn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSAiringStackedFalse {
            get {
                return ResourceManager.GetString("TBSAiringStackedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;Name&quot;:&quot;Our Other Cops Is On !, Part 2&quot;,&quot;Type&quot;:&quot;Episode (Non-Animated)&quot;,&quot;Brand&quot;:&quot;TBS&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2013-09-11T11:30:00Z&quot;,&quot;AiringId&quot;:7108144,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1223,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-14&quot;,&quot;Description&quot;:&quot;D,L,S,V&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;When Randy is about to turn off the prison TV, another Camden episode of \&quot;COPS\&quot; is shown, this time it evolves around the events on Independence Day.&quot;,&quot;Short&quot;:&quot;When Randy is about to turn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSAiringStackedTrue {
            get {
                return ResourceManager.GetString("TBSAiringStackedTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;Name&quot;:&quot;Our Other Cops Is On !, Part 2&quot;,&quot;Type&quot;:&quot;Episode (Non-Animated)&quot;,&quot;Brand&quot;:&quot;TBS&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2013-09-11T11:30:00Z&quot;,&quot;AiringId&quot;:7108144,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1223,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-14&quot;,&quot;Description&quot;:&quot;D,L,S,V&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;When Randy is about to turn off the prison TV, another Camden episode of \&quot;COPS\&quot; is shown, this time it evolves around the events on Independence Day.&quot;,&quot;Short&quot;:&quot;When Randy is about to turn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSAiringWithSingleFlight {
            get {
                return ResourceManager.GetString("TBSAiringWithSingleFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;Name&quot;:&quot;Our Other Cops Is On !, Part 2&quot;,&quot;Type&quot;:&quot;Episode (Non-Animated)&quot;,&quot;Brand&quot;:&quot;TBS&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2013-09-11T11:30:00Z&quot;,&quot;AiringId&quot;:7108144,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1223,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-14&quot;,&quot;Description&quot;:&quot;D,L,S,V&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;When Randy is about to turn off the prison TV, another Camden episode of \&quot;COPS\&quot; is shown, this time it evolves around the events on Independence Day.&quot;,&quot;Short&quot;:&quot;When Randy is about to turn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSAiringWithValidProduct {
            get {
                return ResourceManager.GetString("TBSAiringWithValidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  {&quot;Name&quot;:&quot;Our Other Cops Is On !, Part 2&quot;,&quot;Type&quot;:&quot;Episode (Non-Animated)&quot;,&quot;Brand&quot;:&quot;TBS&quot;,&quot;Platform&quot;:&quot;Broadband&quot;,&quot;Airings&quot;:[{&quot;Date&quot;:&quot;2013-09-11T11:30:00Z&quot;,&quot;AiringId&quot;:7108144,&quot;Linked&quot;:true}],&quot;Duration&quot;:{&quot;LengthInSeconds&quot;:1223,&quot;DisplayMinutes&quot;:30},&quot;Title&quot;:{&quot;Rating&quot;:{&quot;Code&quot;:&quot;TV-14&quot;,&quot;Description&quot;:&quot;D,L,S,V&quot;},&quot;StoryLine&quot;:{&quot;Long&quot;:&quot;When Randy is about to turn off the prison TV, another Camden episode of \&quot;COPS\&quot; is shown, this time it evolves around the events on Independence Day.&quot;,&quot;Short&quot;:&quot;When Randy is about to turn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TBSAiringWithValidProductAndNoDestination {
            get {
                return ResourceManager.GetString("TBSAiringWithValidProductAndNoDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {&quot;TitleIds&quot;:[1234,&quot;3456&quot;],&quot;DestinationCode&quot;:&quot;TNTW&quot;,&quot;Type&quot;:&quot;CSC-MTR&quot;,&quot;PackageData&quot;:{&quot;PackageName&quot;:&quot;TestPackageUpdated&quot;,&quot;TestArray&quot;:[12345,1235,76544,2314213,12312,3123123],&quot;TestObect&quot;:{&quot;ObjectData&quot;:[{&quot;Key&quot;:5,&quot;Value&quot;:&quot;TestValue&quot;},{&quot;Key&quot;:&quot;SomeKey&quot;,&quot;Value&quot;:1234}],&quot;AnotherProperty&quot;:1234.5134}}}.
        /// </summary>
        public static string ValidPackage {
            get {
                return ResourceManager.GetString("ValidPackage", resourceCulture);
            }
        }
    }
}
