version: "2"
services:
  odtapi:
    image: quay.io/turner/odt-api:1.0.0.1866
    ports:
    - 80:5000
    - 443:5000
    environment:
      ASPNETCORE_ENVIRONMENT: sandbox
      HEALTHCHECK: /healthcheck      

  odtjobs:
    image: quay.io/turner/odt-jobs:1.0.0.1866
    ports:
    - 80:5000
    environment:
      ASPNETCORE_ENVIRONMENT: sandbox
      HEALTHCHECK: /healthcheck      

  odtwebapp:
    image: quay.io/turner/odt-portal:1.0.0.1866
    ports:
    - 80:5000
    environment:
      ASPNETCORE_ENVIRONMENT: sandbox
      HEALTHCHECK: /healthcheck      
